import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>New On Windows</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <main>
        <Layout>
          <Sider  className="text-white bg-slate-900"><Sidebar/></Sider>
          <Layout>
            <Header>
              <h1 className="text-center text-3xl py-4">
                <span className="text-red-500">New </span>
                <span className="text-green-500">On </span>
                <span className="text-blue-500">Win</span>
                <span className="text-yellow-500">dows</span>
              </h1>
            </Header>
            <Content>Content</Content>
            <Footer>Footer</Footer>
          </Layout>
        </Layout>
      </main> */}
    </>
  );
}
